layout_spectrum: 0.6346526
color:
  saturation: 0.9983888
  brandStrength: 0.7218563
  lightness: 0.9253491
  rhythmicContrast: 0.437926
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
typography_spectrum: 0.715784
name: Olgapopova.net
